package com.example.druiddemo.dao;

import com.example.druiddemo.model.Reader;
import com.example.druiddemo.model.ReaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    long countByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    int deleteByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    List<Reader> selectByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Reader record, @Param("example") ReaderExample example);
}