package com.example.druiddemo.dao;

import com.example.druiddemo.model.TbBook;
import com.example.druiddemo.model.TbBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    long countByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    int deleteByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    int insert(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    int insertSelective(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    List<TbBook> selectByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbBook record, @Param("example") TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbBook record, @Param("example") TbBookExample example);
}