package com.example.druiddemo.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_book
 */
public class TbBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.reader
     *
     * @mbg.generated
     */
    private String reader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.isbn
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_book
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.id
     *
     * @return the value of tb_book.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.id
     *
     * @param id the value for tb_book.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.reader
     *
     * @return the value of tb_book.reader
     *
     * @mbg.generated
     */
    public String getReader() {
        return reader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.reader
     *
     * @param reader the value for tb_book.reader
     *
     * @mbg.generated
     */
    public void setReader(String reader) {
        this.reader = reader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.isbn
     *
     * @return the value of tb_book.isbn
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.isbn
     *
     * @param isbn the value for tb_book.isbn
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.title
     *
     * @return the value of tb_book.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.title
     *
     * @param title the value for tb_book.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.author
     *
     * @return the value of tb_book.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.author
     *
     * @param author the value for tb_book.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.description
     *
     * @return the value of tb_book.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.description
     *
     * @param description the value for tb_book.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}